# Form implementation generated from reading ui file 'interface_demo2/addPr.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddForn(object):
    def setupUi(self, AddForn):
        AddForn.setObjectName("AddForn")
        AddForn.resize(534, 723)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddForn.sizePolicy().hasHeightForWidth())
        AddForn.setSizePolicy(sizePolicy)
        AddForn.setMinimumSize(QtCore.QSize(534, 723))
        AddForn.setMaximumSize(QtCore.QSize(534, 723))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.jfif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AddForn.setWindowIcon(icon)
        AddForn.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Segoe UI\";")
        self.label = QtWidgets.QLabel(parent=AddForn)
        self.label.setGeometry(QtCore.QRect(180, 20, 191, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=AddForn)
        self.widget.setGeometry(QtCore.QRect(30, 70, 481, 581))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.namePr_line = QtWidgets.QLineEdit(parent=self.widget)
        self.namePr_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.namePr_line.setObjectName("namePr_line")
        self.verticalLayout.addWidget(self.namePr_line)
        self.partn_price_line = QtWidgets.QLineEdit(parent=self.widget)
        self.partn_price_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.partn_price_line.setObjectName("partn_price_line")
        self.verticalLayout.addWidget(self.partn_price_line)
        self.article_line = QtWidgets.QLineEdit(parent=self.widget)
        self.article_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.article_line.setObjectName("article_line")
        self.verticalLayout.addWidget(self.article_line)
        self.descr_line = QtWidgets.QTextEdit(parent=self.widget)
        self.descr_line.setObjectName("descr_line")
        self.verticalLayout.addWidget(self.descr_line)
        self.material_cb = QtWidgets.QComboBox(parent=self.widget)
        self.material_cb.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.material_cb.setObjectName("material_cb")
        self.verticalLayout.addWidget(self.material_cb)
        self.model_cb = QtWidgets.QComboBox(parent=self.widget)
        self.model_cb.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.model_cb.setObjectName("model_cb")
        self.verticalLayout.addWidget(self.model_cb)
        self.typePr_cb = QtWidgets.QComboBox(parent=self.widget)
        self.typePr_cb.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.typePr_cb.setObjectName("typePr_cb")
        self.verticalLayout.addWidget(self.typePr_cb)
        self.widget1 = QtWidgets.QWidget(parent=AddForn)
        self.widget1.setGeometry(QtCore.QRect(80, 670, 401, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.add_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.back_btn = QtWidgets.QPushButton(parent=self.widget1)
        self.back_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)

        self.retranslateUi(AddForn)
        QtCore.QMetaObject.connectSlotsByName(AddForn)

    def retranslateUi(self, AddForn):
        _translate = QtCore.QCoreApplication.translate
        AddForn.setWindowTitle(_translate("AddForn", "Добавление мебели"))
        self.label.setText(_translate("AddForn", "Добавить мебель"))
        self.namePr_line.setPlaceholderText(_translate("AddForn", "Введите название мебели"))
        self.partn_price_line.setPlaceholderText(_translate("AddForn", "Минимальная цена для партнера"))
        self.article_line.setPlaceholderText(_translate("AddForn", "Артикул"))
        self.descr_line.setPlaceholderText(_translate("AddForn", "Введите описание мебели"))
        self.add_btn.setText(_translate("AddForn", "Добавить"))
        self.back_btn.setText(_translate("AddForn", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddForn = QtWidgets.QWidget()
    ui = Ui_AddForn()
    ui.setupUi(AddForn)
    AddForn.show()
    sys.exit(app.exec())
