# Form implementation generated from reading ui file 'interface_demo2/aquth.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthForm(object):
    def setupUi(self, AuthForm):
        AuthForm.setObjectName("AuthForm")
        AuthForm.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        AuthForm.resize(551, 556)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthForm.sizePolicy().hasHeightForWidth())
        AuthForm.setSizePolicy(sizePolicy)
        AuthForm.setMinimumSize(QtCore.QSize(551, 556))
        AuthForm.setMaximumSize(QtCore.QSize(551, 556))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.jfif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AuthForm.setWindowIcon(icon)
        AuthForm.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=AuthForm)
        self.label.setGeometry(QtCore.QRect(200, 130, 161, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(parent=AuthForm)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 440, 223, 40))
        self.pushButton_2.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(parent=AuthForm)
        self.label_2.setGeometry(QtCore.QRect(250, 400, 111, 31))
        self.label_2.setStyleSheet("font: 8pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=AuthForm)
        self.widget.setGeometry(QtCore.QRect(90, 190, 391, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_line = QtWidgets.QLineEdit(parent=self.widget)
        self.login_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.login_line.setObjectName("login_line")
        self.verticalLayout.addWidget(self.login_line)
        self.passw_line = QtWidgets.QLineEdit(parent=self.widget)
        self.passw_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.passw_line.setObjectName("passw_line")
        self.verticalLayout.addWidget(self.passw_line)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(AuthForm)
        QtCore.QMetaObject.connectSlotsByName(AuthForm)

    def retranslateUi(self, AuthForm):
        _translate = QtCore.QCoreApplication.translate
        AuthForm.setWindowTitle(_translate("AuthForm", "Авторизация"))
        self.label.setText(_translate("AuthForm", "Авторизация"))
        self.pushButton_2.setText(_translate("AuthForm", "Зарегистрироваться"))
        self.label_2.setText(_translate("AuthForm", "Нет аккаунта?"))
        self.login_line.setPlaceholderText(_translate("AuthForm", "Введите email"))
        self.passw_line.setPlaceholderText(_translate("AuthForm", "Введите пароль"))
        self.pushButton.setText(_translate("AuthForm", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthForm = QtWidgets.QWidget()
    ui = Ui_AuthForm()
    ui.setupUi(AuthForm)
    AuthForm.show()
    sys.exit(app.exec())
