# Form implementation generated from reading ui file 'interface_demo2/calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FunctionForm(object):
    def setupUi(self, FunctionForm):
        FunctionForm.setObjectName("FunctionForm")
        FunctionForm.resize(505, 506)
        FunctionForm.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label = QtWidgets.QLabel(parent=FunctionForm)
        self.label.setGeometry(QtCore.QRect(140, 10, 231, 31))
        self.label.setObjectName("label")
        self.result = QtWidgets.QLabel(parent=FunctionForm)
        self.result.setGeometry(QtCore.QRect(80, 370, 401, 51))
        self.result.setObjectName("result")
        self.pushButton = QtWidgets.QPushButton(parent=FunctionForm)
        self.pushButton.setGeometry(QtCore.QRect(390, 460, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=FunctionForm)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 460, 141, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(parent=FunctionForm)
        self.widget.setGeometry(QtCore.QRect(70, 70, 411, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.typePr_cb = QtWidgets.QComboBox(parent=self.widget)
        self.typePr_cb.setObjectName("typePr_cb")
        self.verticalLayout.addWidget(self.typePr_cb)
        self.typeMat_cb = QtWidgets.QComboBox(parent=self.widget)
        self.typeMat_cb.setObjectName("typeMat_cb")
        self.verticalLayout.addWidget(self.typeMat_cb)
        self.count_mat = QtWidgets.QLineEdit(parent=self.widget)
        self.count_mat.setObjectName("count_mat")
        self.verticalLayout.addWidget(self.count_mat)
        self.par1 = QtWidgets.QLineEdit(parent=self.widget)
        self.par1.setObjectName("par1")
        self.verticalLayout.addWidget(self.par1)
        self.par2 = QtWidgets.QLineEdit(parent=self.widget)
        self.par2.setObjectName("par2")
        self.verticalLayout.addWidget(self.par2)

        self.retranslateUi(FunctionForm)
        QtCore.QMetaObject.connectSlotsByName(FunctionForm)

    def retranslateUi(self, FunctionForm):
        _translate = QtCore.QCoreApplication.translate
        FunctionForm.setWindowTitle(_translate("FunctionForm", "Каклькулятор расходов"))
        self.label.setText(_translate("FunctionForm", "Рассчитать расходы сырья"))
        self.result.setText(_translate("FunctionForm", "TextLabel"))
        self.pushButton.setText(_translate("FunctionForm", "Назад"))
        self.pushButton_2.setText(_translate("FunctionForm", "Рассчитать"))
        self.count_mat.setPlaceholderText(_translate("FunctionForm", "Введите количество сырья"))
        self.par1.setPlaceholderText(_translate("FunctionForm", "Параметр 1"))
        self.par2.setPlaceholderText(_translate("FunctionForm", "Параметр 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FunctionForm = QtWidgets.QWidget()
    ui = Ui_FunctionForm()
    ui.setupUi(FunctionForm)
    FunctionForm.show()
    sys.exit(app.exec())
