# Form implementation generated from reading ui file 'interface_demo2/edit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditForm(object):
    def setupUi(self, EditForm):
        EditForm.setObjectName("EditForm")
        EditForm.resize(511, 697)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditForm.sizePolicy().hasHeightForWidth())
        EditForm.setSizePolicy(sizePolicy)
        EditForm.setMinimumSize(QtCore.QSize(511, 697))
        EditForm.setMaximumSize(QtCore.QSize(511, 697))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.jfif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EditForm.setWindowIcon(icon)
        EditForm.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \"Segoe UI\";\n"
"")
        self.label = QtWidgets.QLabel(parent=EditForm)
        self.label.setGeometry(QtCore.QRect(150, 10, 191, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=EditForm)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 481, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.namePr_line = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.namePr_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.namePr_line.setObjectName("namePr_line")
        self.verticalLayout.addWidget(self.namePr_line)
        self.partn_price_line = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.partn_price_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.partn_price_line.setObjectName("partn_price_line")
        self.verticalLayout.addWidget(self.partn_price_line)
        self.article_line = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.article_line.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.article_line.setObjectName("article_line")
        self.verticalLayout.addWidget(self.article_line)
        self.descr_line = QtWidgets.QTextEdit(parent=self.layoutWidget)
        self.descr_line.setObjectName("descr_line")
        self.verticalLayout.addWidget(self.descr_line)
        self.material_cb = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.material_cb.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.material_cb.setObjectName("material_cb")
        self.verticalLayout.addWidget(self.material_cb)
        self.model_cb = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.model_cb.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.model_cb.setObjectName("model_cb")
        self.verticalLayout.addWidget(self.model_cb)
        self.typePr_cb = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.typePr_cb.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.typePr_cb.setObjectName("typePr_cb")
        self.verticalLayout.addWidget(self.typePr_cb)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=EditForm)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 650, 401, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_btn = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.edit_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        self.delete_btn = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.delete_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.back_btn = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.back_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)

        self.retranslateUi(EditForm)
        QtCore.QMetaObject.connectSlotsByName(EditForm)

    def retranslateUi(self, EditForm):
        _translate = QtCore.QCoreApplication.translate
        EditForm.setWindowTitle(_translate("EditForm", "Редактирование"))
        self.label.setText(_translate("EditForm", "Редактировать"))
        self.namePr_line.setPlaceholderText(_translate("EditForm", "Введите название мебели"))
        self.partn_price_line.setPlaceholderText(_translate("EditForm", "Минимальная цена для партнера"))
        self.article_line.setPlaceholderText(_translate("EditForm", "Артикул"))
        self.descr_line.setPlaceholderText(_translate("EditForm", "Введите описание мебели"))
        self.edit_btn.setText(_translate("EditForm", "Отредактировать"))
        self.delete_btn.setText(_translate("EditForm", "Удалить"))
        self.back_btn.setText(_translate("EditForm", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditForm = QtWidgets.QWidget()
    ui = Ui_EditForm()
    ui.setupUi(EditForm)
    EditForm.show()
    sys.exit(app.exec())
