# Form implementation generated from reading ui file 'interface_demo2/main_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.resize(1388, 782)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)
        MainForm.setMinimumSize(QtCore.QSize(1388, 782))
        MainForm.setMaximumSize(QtCore.QSize(1388, 782))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.jfif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainForm.setWindowIcon(icon)
        MainForm.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label = QtWidgets.QLabel(parent=MainForm)
        self.label.setGeometry(QtCore.QRect(540, 10, 341, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(parent=MainForm)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 1361, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.models_cb = QtWidgets.QComboBox(parent=self.tab)
        self.models_cb.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.models_cb.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.models_cb.setObjectName("models_cb")
        self.products_lw = QtWidgets.QListWidget(parent=self.tab)
        self.products_lw.setGeometry(QtCore.QRect(20, 70, 1301, 551))
        self.products_lw.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);")
        self.products_lw.setObjectName("products_lw")
        self.addPr_btn = QtWidgets.QPushButton(parent=self.tab)
        self.addPr_btn.setGeometry(QtCore.QRect(20, 630, 191, 31))
        self.addPr_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.addPr_btn.setObjectName("addPr_btn")
        self.type_pr_cb = QtWidgets.QComboBox(parent=self.tab)
        self.type_pr_cb.setGeometry(QtCore.QRect(320, 20, 281, 31))
        self.type_pr_cb.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.type_pr_cb.setObjectName("type_pr_cb")
        self.next_page_btn = QtWidgets.QPushButton(parent=self.tab)
        self.next_page_btn.setGeometry(QtCore.QRect(1190, 640, 151, 31))
        self.next_page_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.next_page_btn.setObjectName("next_page_btn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.products_cb = QtWidgets.QComboBox(parent=self.tab_2)
        self.products_cb.setGeometry(QtCore.QRect(10, 10, 341, 31))
        self.products_cb.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.products_cb.setObjectName("products_cb")
        self.workshops_lw = QtWidgets.QListWidget(parent=self.tab_2)
        self.workshops_lw.setGeometry(QtCore.QRect(10, 60, 1331, 591))
        self.workshops_lw.setStyleSheet("background-color: rgb(244, 232, 211);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.workshops_lw.setObjectName("workshops_lw")
        self.back_btn = QtWidgets.QPushButton(parent=self.tab_2)
        self.back_btn.setGeometry(QtCore.QRect(10, 660, 151, 31))
        self.back_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.procedure_btn = QtWidgets.QPushButton(parent=self.tab_2)
        self.procedure_btn.setGeometry(QtCore.QRect(180, 660, 241, 28))
        self.procedure_btn.setStyleSheet("background-color: rgb(103, 186, 128);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.procedure_btn.setObjectName("procedure_btn")
        self.tabWidget.addTab(self.tab_2, "")
        self.exit_btn = QtWidgets.QPushButton(parent=MainForm)
        self.exit_btn.setGeometry(QtCore.QRect(1290, 10, 93, 28))
        self.exit_btn.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(MainForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "Система учета продукции"))
        self.label.setText(_translate("MainForm", "Система учета мебельной продукции"))
        self.addPr_btn.setText(_translate("MainForm", "Добавить продукцию"))
        self.next_page_btn.setText(_translate("MainForm", "Следующая стр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainForm", "Продукция"))
        self.back_btn.setText(_translate("MainForm", "Назад"))
        self.procedure_btn.setText(_translate("MainForm", "Рассчитать расходы сырья"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainForm", "Цеха"))
        self.exit_btn.setText(_translate("MainForm", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainForm = QtWidgets.QWidget()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec())
